version: "3.1"
services:
    postgres:
      image: postgres:${POSTGRES_VERSION}
      container_name: ${CONTAINER_NAME}-postgres
      working_dir: /application
      volumes:
        - ../:/application
        - ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql
        - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d

      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      ports:
        - "${POSTGRES_PORT}:5432"
      networks:
        - internal

    nginx:
      image: nginx:alpine
      container_name: ${CONTAINER_NAME}-nginx
      working_dir: /application
      volumes:
          - ../:/application
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "${WEB_HTTP_PORT}:80"
       - "${WEB_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      networks:
        - internal

    php-fpm:
      build:
        context: php-fpm
        args:
          - INSTALL_SYMFONY=${INSTALL_SYMFONY}
          - INSTALL_XDEBUG=${INSTALL_XDEBUG}
      container_name: ${CONTAINER_NAME}-php-fpm
      working_dir: /application
      environment:
        PHP_IDE_CONFIG: "serverName=${CONTAINER_NAME}"
        #- PHP_IDE_CONFIG="serverName=${CONTAINER_NAME}"
      volumes:
        - ../:/application
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      networks:
        - internal

    rabbitmq:
      image: "rabbitmq:3-management"
      container_name: ${CONTAINER_NAME}-rabbitmq
      working_dir: /application
      ports:
        - "5672:5672"
        - "15672:15672"
      volumes:
        - 'rabbitmq_data:/data'
      networks:
        - internal

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
      container_name: ${CONTAINER_NAME}-elasticsearch
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - 9200:9200
        - 9300:9300
      networks:
        - internal

### Networks Setup ############################################

networks:
  internal:
    driver: "bridge"

### Volumes Setup #############################################

volumes:
  postgres:
    driver: "local"
  rabbitmq_data:
